### ISSUE TITLE
Adding to Electronic-Interchange-Github-Resources

### ISSUE THREAD

**Issue by michaelachrisco** [walmartlabs/gozer#25]
Hello, I am trying to compile as many EDI resources as possible through Github and I stumbled upon this repo. 

Do you mind if I add a reference to this repo to [michaelachrisco/Electronic-Interchange-Github-Resources](https://github.com/michaelachrisco/Electronic-Interchange-Github-Resources) ?

**Comment by CodeSmell** [comment]
Michael, thanks for your interest in Gozer, and checking it out. 
Please feel free to add this repo to your list.
